#!/bin/zsh
mkdir -p ~/.aws
$CONTAINER_TOOL run \
  --rm \
  $([[ ! -z "$AWS_PROFILE" ]] && echo "-e AWS_PROFILE=$AWS_PROFILE") \
  $([[ ! -z "$AWS_ACCESS_KEY_ID" ]] && echo "-e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID") \
  $([[ ! -z "$AWS_SECRET_ACCESS_KEY" ]] && echo "-e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY") \
  $([[ ! -z "$AWS_DEFAULT_REGION" ]] && echo "-e AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION") \
  $([[ ! -z "$AWS_SESSION_TOKEN" ]] && echo "-e AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN") \
  $([[ ! -z "$AWS_SECURITY_TOKEN" ]] && echo "-e AWS_SECURITY_TOKEN=$AWS_SECURITY_TOKEN") \
  -v "$HOME/.aws:/root/.aws:rw" \
  -v "$(pwd):/aws:rw" \
  amazon/aws-cli $@
