#!/usr/bin/env zsh
mkdir -p $HOME/.cache/pre-commit
podman run \
    $([[ -t 1 ]] && echo -it) \
    --rm \
    -v "$HOME/.cache/pre-commit:/cache/pre-commit" \
    -v "$(pwd):/project" \
    -e XDG_CACHE_HOME=/cache \
    --name pre-commit \
    pre-commid "$@"
