#!/bin/zsh
$CONTAINER_TOOL run \
  --rm \
  -it \
  -u $(id -u ${USER}):$(id -g ${USER}) \
  --net host \
  -w /app \
  -v "$(pwd):/app:rw" \
  --env POSTGRES_HOST \
  --env POSTGRES_USER \
  --env GITLAB_TOKEN \
  node:14-buster yarn $@