#!/usr/bin/env bash

$CONTAINER_TOOL run \
  --rm \
  -u $(id -u ${USER}):$(id -g ${USER})  \
  -w /app \
  -v "$(pwd):/terraform-docs:rw" \
  quay.io/terraform-docs/terraform-docs:0.17.0 markdown /terraform-docs

# docker run --rm --volume "$(pwd):/terraform-docs" -u $(id -u) quay.io/terraform-docs/terraform-docs:0.19.0 markdown /terraform-docs
