#!/usr/bin/env zsh

antidote_dir=~/.antidote
source $antidote_dir/antidote.zsh
antidote update

rustup update
cargo install-update --all

if [[ "$TERMINAL_OS" == "macos" ]]; then
    brew update
    brew upgrade
    brew upgrade --cask --greedy

elif [[ "$TERMINAL_OS" == "ubuntu" ]]; then
    sudo apt update && sudo apt upgrade && sudo apt autoremove

elif [[ "$TERMINAL_OS" == "fedora" ]]; then
    sudo dnf upgrade --refresh

elif [[ "$TERMINAL_OS" == "arch" ]]; then
    sudo pacman -Syu

fi
