format = "$time$all"
add_newline = false

[time]
format = "[$time]($style) "
style = "bold blue"
disabled = false

[cmd_duration]
min_time = 500

[aws]
symbol = ''

[python]
symbol = ''
style = "bold green"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) in '
contexts = [
  { context_pattern = ".*qa.*", style = "yellow bold", symbol = "⚠️ " },
  { context_pattern = ".*prd.*", style = "red bold", symbol = "⚠️ " },
]

[helm]
disabled = false

[terraform]
disabled = false

[container]
disabled = true

[hostname]
disabled = false
ssh_only = false
