format = "$time$all"
add_newline = false

[time]
format = "[$time]($style) "
disabled = false

[cmd_duration]
min_time = 500

[kubernetes]
disabled = true

[aws]
format = "(on [$symbol$profile]($style) )"
