format = "$all"
add_newline = false

[time]
disabled = true

[line_break]
disabled = true

[gcloud]
disabled = true

[docker_context]
disabled = true

[git_status]
disabled = true

[cmd_duration]
min_time = 500

[aws]
symbol = ''

[python]
disabled = true
symbol = ''
style = "bold green"

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style) in '
contexts = [
  { context_pattern = ".*qa.*", style = "yellow bold", symbol = "⚠️ " },
  { context_pattern = ".*prd.*", style = "red bold", symbol = "⚠️ " },
]

[helm]
disabled = false

[terraform]
disabled = false

[container]
disabled = true

[hostname]
disabled = false
ssh_only = true
