format = "$time$all"
add_newline = false

[time]
format = "[$time]($style) "
style = "bold blue"
disabled = false

[cmd_duration]
min_time = 500

[aws]
symbol = ''

[python]
symbol = ''
style = "bold green"

[kubernetes]
disabled = true

[container]
disabled = true

[hostname]
disabled = false
ssh_only = false